//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuildInspectEntities : DbContext
    {
        public BuildInspectEntities()
            : base("name=BuildInspectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chklst_item_master> chklst_item_master { get; set; }
        public virtual DbSet<chklst_trn_detail> chklst_trn_detail { get; set; }
        public virtual DbSet<chklst_trn_files> chklst_trn_files { get; set; }
        public virtual DbSet<company_master> company_master { get; set; }
        public virtual DbSet<company_module_mapping> company_module_mapping { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<screen> screens { get; set; }
        public virtual DbSet<service_form_files> service_form_files { get; set; }
        public virtual DbSet<servicetype_master> servicetype_master { get; set; }
        public virtual DbSet<usergroup> usergroups { get; set; }
        public virtual DbSet<usergroup_screen_mapping> usergroup_screen_mapping { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usergroup_menu_mapping> usergroup_menu_mapping { get; set; }
        public virtual DbSet<building_master> building_master { get; set; }
        public virtual DbSet<project_master> project_master { get; set; }
        public virtual DbSet<checklist_files> checklist_files { get; set; }
        public virtual DbSet<chklst_trn_master> chklst_trn_master { get; set; }
        public virtual DbSet<deployment> deployments { get; set; }
        public virtual DbSet<License_Master> License_Master { get; set; }
        public virtual DbSet<school_user_mapping> school_user_mapping { get; set; }
        public virtual DbSet<service_form> service_form { get; set; }
        public virtual DbSet<sys_freqTable> sys_freqTable { get; set; }
        public virtual DbSet<chklst_item_title_master> chklst_item_title_master { get; set; }
        public virtual DbSet<chklstitem_child_master> chklstitem_child_master { get; set; }
    }
}
