//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class chklst_item_title_master
    {
        public int chklstitemId { get; set; }
        public Nullable<int> ChkLstTypeId { get; set; }
        public string CheckListType { get; set; }
        public string Frequency { get; set; }
        public string FormName { get; set; }
        public string TitleDescription { get; set; }
    }
}
