//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class chklst_trn_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chklst_trn_master()
        {
            this.chklst_trn_detail = new HashSet<chklst_trn_detail>();
            this.chklst_trn_files = new HashSet<chklst_trn_files>();
        }
    
        public int CLTMID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CheckedBy_Signature { get; set; }
        public string VerifiedBy_Signature { get; set; }
        public string EndoresBy_Signature { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> PrjMasID { get; set; }
        public Nullable<int> Draft_Flag { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> User_Sign_Date { get; set; }
        public Nullable<System.DateTime> OpMngr_Sign_Date { get; set; }
        public Nullable<System.DateTime> MA_Sign_Date { get; set; }
        public string CheckedBy_Remarks { get; set; }
        public string VerifiedBy_Remarks { get; set; }
        public string EndoresBy_Remarks { get; set; }
        public Nullable<int> Status_Flag { get; set; }
        public string CLType { get; set; }
        public Nullable<System.DateTime> CheckedBy_DateTime { get; set; }
        public Nullable<System.DateTime> VerifiedBy_DateTime { get; set; }
        public Nullable<System.DateTime> EndoresBy_DateTime { get; set; }
        public Nullable<decimal> CB_Latitude { get; set; }
        public Nullable<decimal> CB_Longitude { get; set; }
        public string CheckedBy_Name { get; set; }
        public string VerifiedBy_Name { get; set; }
        public string EndoresBy_Name { get; set; }
        public Nullable<System.DateTime> CLMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chklst_trn_detail> chklst_trn_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chklst_trn_files> chklst_trn_files { get; set; }
        public virtual chklst_trn_master chklst_trn_master1 { get; set; }
        public virtual chklst_trn_master chklst_trn_master2 { get; set; }
    }
}
