//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_module_mapping
    {
        public int Id { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> Access { get; set; }
    }
}
