//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class deployment
    {
        public int DeployID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Schedule_Date { get; set; }
        public Nullable<int> Is_Completed { get; set; }
        public Nullable<System.DateTime> Completed_Date { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
