//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int ModuleID { get; set; }
        public int AccessType { get; set; }
        public string MenuName { get; set; }
        public int Order_By { get; set; }
    }
}
