//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_master
    {
        public int PrjMasID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public string MonthName { get; set; }
        public Nullable<System.DateTime> Month_Start_Date { get; set; }
        public Nullable<System.DateTime> Month_End_Date { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> Lift_Count { get; set; }
        public Nullable<int> Is_Completed { get; set; }
        public Nullable<int> Is_Rescheduled { get; set; }
        public Nullable<System.DateTime> Rescheduled_Date { get; set; }
        public string Rescheduled_Remarks { get; set; }
        public string CLType { get; set; }
        public string Lift_Opr_Name { get; set; }
        public Nullable<int> Fan_Count { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
