//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class school_user_mapping
    {
        public int SUID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CLType { get; set; }
    }
}
