//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class screen
    {
        public int SCREEN_ID { get; set; }
        public int MENUID { get; set; }
        public string SCREEN_NAME { get; set; }
        public string SCREEN_CLASS_NAME { get; set; }
        public string SCREEN_URL { get; set; }
        public int ORDER_BY { get; set; }
        public Nullable<int> MODULEID { get; set; }
        public Nullable<int> ScreenID { get; set; }
    }
}
