//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_freqTable
    {
        public int Id { get; set; }
        public Nullable<int> MonthNum { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> CalendarMonthNum { get; set; }
    }
}
