//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInspect.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string UID { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string ServiceType { get; set; }
        public string Zone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public Nullable<int> TeamLead_ID { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public Nullable<int> ProjMngr_ID { get; set; }
        public string DeviceID { get; set; }
    
        public virtual company_master company_master { get; set; }
        public virtual usergroup usergroup { get; set; }
    }
}
